language: ruby
cache: bundler
rvm:
  - 2.3.1
git:
  submodules: false
env:
  global:
    - RACK_ENV=test
services:
  - postgresql
  - rabbitmq
notifications:
  email:
    recipients:
      - deangalvin3@gmail.com
    on_success: change
    on_failure: always
branches:
  only:
    - master
install:
  - bundle install
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp db/config.travis.yml db/config.yml
script:
  - RAILS_ENV=test bundle exec rake db:create --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rspec --color -p
  - bundle exec rubocop
